### ISSUE TITLE
Sensor not working - BadAuthentication

### ISSUE THREAD

**Issue by BebeMischa** [PiotrMachowski/Home-Assistant-custom-components-Google-Keep#28] opened 2022-05-14 13:51 UTC
Out of nothing my sensor stopped working.

```
Logger: homeassistant.components.sensor
Source: custom_components/google_keep/sensor.py:39
Integration: Sensor (documentation, issues)
First occurred: 06:07:46 (1 occurrences)
Last logged: 06:07:46

Error while setting up google_keep platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 249, in _async_setup_platform
    await asyncio.shield(task)
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/google_keep/sensor.py", line 39, in setup_platform
    login_success = keep.login(username, password)
  File "/usr/local/lib/python3.9/site-packages/gkeepapi/__init__.py", line 693, in login
    ret = auth.login(username, password, get_mac())
  File "/usr/local/lib/python3.9/site-packages/gkeepapi/__init__.py", line 59, in login
    raise exception.LoginException(
gkeepapi.exception.LoginException: ('BadAuthentication', None)
```

Nothing has changed in my logins...

Any idea?

**Comment by PiotrMachowski** [comment] 2022-05-14 14:48
Duplicate of #15

**Closed by PiotrMachowski** 2022-05-14 14:48 UTC
