### ISSUE TITLE
Sensor not working since 2022.5.4

### ISSUE THREAD

**Issue by Roei639** [PiotrMachowski/Home-Assistant-custom-components-Google-Keep#27] opened 2022-05-13 16:41 UTC
The sensor stopped working

log:
Logger: homeassistant.components.sensor
Source: custom_components/google_keep/sensor.py:39
Integration: חיישן (documentation, issues)
First occurred: 16:11:45 (1 occurrences)
Last logged: 16:11:45

Error while setting up google_keep platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 249, in _async_setup_platform
    await asyncio.shield(task)
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/google_keep/sensor.py", line 39, in setup_platform
    login_success = keep.login(username, password)
  File "/usr/local/lib/python3.9/site-packages/gkeepapi/__init__.py", line 693, in login
    ret = auth.login(username, password, get_mac())
  File "/usr/local/lib/python3.9/site-packages/gkeepapi/__init__.py", line 59, in login
    raise exception.LoginException(
gkeepapi.exception.LoginException: ('NeedsBrowser', 'To access your account, you must sign in on the web. Touch Next to start browser sign-in.')

**Comment by ejpenney** [comment] 2022-05-13 21:28
Same here, upgrading to 2022.5.4 caused the same errors in my Logs.  Reverting did NOT fix it.

**Comment by PiotrMachowski** [comment] 2022-05-13 23:51
This error doesn't seem to be related to 2022.5.4, probably even a restart would break it
https://github.com/kiwiz/gkeepapi/issues/123

**Comment by PiotrMachowski** [comment] 2022-05-14 14:47
Duplicate of #26

**Closed by PiotrMachowski** 2022-05-14 14:47 UTC
